/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 11 20:08:35 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import custom_classes.Currencies;
import custom_classes.Dates;
import custom_classes.Id;
import custom_classes.Participants;
import custom_classes.Price;
import custom_classes.Transactions;
import custom_classes.TripNames;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.deleteEditTransactionPage()V: Line 171
   * Goal 3. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 4. main.ClassUnderTestApogen.formNewTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Participants;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 138
   * Goal 5. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 6. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 7. main.ClassUnderTestApogen.goToEditTransactionPageTransactionsPage(Lcustom_classes/Id;)V: Line 496
   * Goal 8. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 9. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 10. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 11. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 12. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 13. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   * Goal 14. main.ClassUnderTestApogen.yesConfirmationPage()V: Line 45
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      Currencies currencies0 = Currencies.USD;
      Participants participants0 = Participants.JOHN;
      Participants participants1 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.LUNCH;
      int int0 = 3913;
      Price price0 = new Price(int0);
      Dates dates0 = Dates.SUMMER;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames0);
      classUnderTestApogen0.yesConfirmationPage();
      TripNames tripNames1 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames1);
      Participants participants2 = Participants.MARK;
      Participants participants3 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants2, participants3);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
      Transactions transactions1 = Transactions.TICKETS;
      classUnderTestApogen0.formNewTransactionPage(transactions1, participants2, price0, dates0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      Id id0 = new Id(price0.value);
      classUnderTestApogen0.goToEditTransactionPageTransactionsPage(id0);
      classUnderTestApogen0.deleteEditTransactionPage();
  }

  //Test case number: 1
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelEditEventPage()V: Line 291
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.goToConfirmDeletionPageEditEventPage()V: Line 329
   * Goal 4. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 5. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 6. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 7. main.ClassUnderTestApogen.noConfirmDeletionPage()V: Line 262
   * Goal 8. main.ClassUnderTestApogen.yesConfirmDeletionPage()V: Line 278
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.CHF;
      Participants participants0 = Participants.MIKE;
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToHomePageHomePage();
      TripNames tripNames1 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToEditEventHomePage(tripNames1);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
      classUnderTestApogen0.cancelEditEventPage();
      classUnderTestApogen0.goToHomePageHomePage();
      TripNames tripNames2 = TripNames.ROME;
      classUnderTestApogen0.goToEditEventHomePage(tripNames2);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
      classUnderTestApogen0.cancelEditEventPage();
      classUnderTestApogen0.goToHomePageHomePage();
      TripNames tripNames3 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToEditEventHomePage(tripNames3);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.yesConfirmDeletionPage();
  }

  //Test case number: 2
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 3. main.ClassUnderTestApogen.cancelNewTransactionPage()V: Line 119
   * Goal 4. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 5. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 6. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 7. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 8. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 9. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 10. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 11. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 12. main.ClassUnderTestApogen.noConfirmationPage()V: Line 30
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames1);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames2 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
      Currencies currencies0 = Currencies.CZK;
      Participants participants0 = Participants.LUKE;
      Participants participants1 = Participants.LUKE;
      Currencies currencies1 = Currencies.GBP;
      Participants participants2 = Participants.MARK;
      classUnderTestApogen0.formNewEventPage(currencies1, participants1, participants2);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
      classUnderTestApogen0.cancelNewTransactionPage();
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames0);
      classUnderTestApogen0.noConfirmationPage();
      TripNames tripNames3 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames3);
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants2);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
  }

  //Test case number: 3
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.closeAddTransactionPage()V: Line 532
   * Goal 3. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 4. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 5. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 6. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 7. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 8. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 9. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 10. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 11. main.ClassUnderTestApogen.noConfirmationPage()V: Line 30
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.AMUSEMENT_PARK;
      Participants participants0 = Participants.MATTEO;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.EUR;
      Participants participants1 = Participants.LUKE;
      Participants participants2 = Participants.MARCO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants1, participants2);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames0);
      classUnderTestApogen0.noConfirmationPage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames1);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames2 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames3 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames3);
      Participants participants3 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants3);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.closeAddTransactionPage();
  }

  //Test case number: 4
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 3. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 4. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 5. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 6. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 7. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames1 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames1);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.PLN;
      Participants participants0 = Participants.MATTEO;
      Participants participants1 = Participants.LUKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToHomePageHomePage();
      TripNames tripNames3 = TripNames.BARCELONA;
      classUnderTestApogen0.goToEditEventHomePage(tripNames3);
      Participants participants2 = Participants.LUKE;
      classUnderTestApogen0.formEditEventPage(currencies0, participants0, participants2);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
  }

  //Test case number: 5
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 4. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 5. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 6. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 7. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   */

  @Test(timeout = 1001000)
  public void test5()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames1 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames1);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames2 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      Currencies currencies0 = Currencies.HRK;
      Participants participants0 = Participants.MARCO;
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Participants participants2 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants2, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      TripNames tripNames3 = TripNames.BARCELONA;
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames3);
  }

  //Test case number: 6
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 4. main.ClassUnderTestApogen.goToHomePageIndexPage(Lcustom_classes/TripNames;)V: Line 404
   * Goal 5. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 6. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 7. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   */

  @Test(timeout = 1001000)
  public void test6()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.RESTAURANT;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Restaurant does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames1 = TripNames.RESTAURANT;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames1);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Restaurant does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.yesConfirmationPage();
      } catch(RuntimeException e) {
         //
         // yesConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames2 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames2);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Trip to Rome does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.yesConfirmationPage();
      } catch(RuntimeException e) {
         //
         // yesConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames3 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames3);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames3);
      Currencies currencies0 = Currencies.RUB;
      Participants participants0 = Participants.MIKE;
      Participants participants1 = Participants.LUKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames4 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames4);
      Currencies currencies1 = Currencies.USD;
      Participants participants2 = Participants.JOHN;
      classUnderTestApogen0.formNewEventPage(currencies1, participants0, participants2);
      TripNames tripNames5 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames5);
      } catch(RuntimeException e) {
         //
         // goToEditEvent: new trip name Trip to Rome already exists
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      } catch(RuntimeException e) {
         //
         // goToConfirmDeletionPageEditEventPage: expected po_apogen.EditEventPage, found HomePage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.yesConfirmDeletionPage();
      } catch(RuntimeException e) {
         //
         // yesConfirmDeletionPage: expected po_apogen.ConfirmDeletionPage, found HomePage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames3);
      } catch(RuntimeException e) {
         //
         // goToNewEventNavbarIndexPage: expected po_apogen.IndexPage, found HomePage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.formNewEventPage(currencies1, participants0, participants1);
      } catch(RuntimeException e) {
         //
         // formNewEventPage: expected po_apogen.NewEventPage, found HomePage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      classUnderTestApogen0.goToIndexPageHomePage();
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames5);
      } catch(RuntimeException e) {
         //
         // goToNewEventHome: tripName Trip to Rome already exists
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelNewEventPage();
      } catch(RuntimeException e) {
         //
         // cancelNewEventPage: expected po_apogen.NewEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames6 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames6);
      Currencies currencies2 = Currencies.CZK;
      Participants participants3 = Participants.MARCO;
      classUnderTestApogen0.formNewEventPage(currencies2, participants1, participants3);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames7 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames7);
      } catch(RuntimeException e) {
         //
         // goToNewEventHome: tripName Trip to Rome already exists
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelNewEventPage();
      } catch(RuntimeException e) {
         //
         // cancelNewEventPage: expected po_apogen.NewEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames8 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToHomePageIndexPage(tripNames8);
      } catch(IllegalStateException e) {
         //
         // HomePage not loaded properly
         //
         //verifyException("po_apogen.HomePage", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToIndexPageHomePage();
      } catch(RuntimeException e) {
         //
         // goToIndexPageHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Restaurant does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames9 = TripNames.AMUSEMENT_PARK;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames9);
      } catch(RuntimeException e) {
         //
         // Expected condition failed: waiting for presence of element located by: By.xpath: //section[@id=\"about\"]//a[text()=\"Create New Event\"] (tried for 5 second(s) with 50 MILLISECONDS interval)
         //
         //verifyException("org.openqa.selenium.support.ui.WebDriverWait", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelNewEventPage();
      } catch(RuntimeException e) {
         //
         // cancelNewEventPage: expected po_apogen.NewEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames1);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Restaurant does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames10 = TripNames.BARCELONA;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames10);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Trip To Barcelona does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToHomePageIndexPage(tripNames8);
      } catch(RuntimeException e) {
         //
         // goToHomePage: tripName Trip to Rome does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToTransactionsHomePage();
      } catch(RuntimeException e) {
         //
         // goToTransactionsHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      int int0 = 214;
      Id id0 = new Id(int0);
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditTransactionPageTransactionsPage(id0);
      } catch(RuntimeException e) {
         //
         // goToEditTransactionPageTransactionsPage: expected po_apogen.TransactionsPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.deleteEditTransactionPage();
      } catch(RuntimeException e) {
         //
         // deleteEditTransactionPage: expected po_apogen.EditTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationTransactionPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationTransactionPage: expected po_apogen.ConfirmationTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
  }
}
