/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 17 20:13:15 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import custom_classes.Currencies;
import custom_classes.Dates;
import custom_classes.Id;
import custom_classes.Participants;
import custom_classes.Price;
import custom_classes.Transactions;
import custom_classes.TripNames;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 3. main.ClassUnderTestApogen.cancelNewTransactionPage()V: Line 119
   * Goal 4. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 5. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 6. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 7. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 8. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 9. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 10. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 11. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 12. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 13. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      TripNames tripNames1 = TripNames.RESTAURANT;
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames1);
      Currencies currencies0 = Currencies.HRK;
      Participants participants0 = Participants.MARCO;
      Participants participants1 = Participants.JOHN;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      int int0 = (-1694);
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.MUSEUM;
      Price price0 = new Price(int0);
      Dates dates0 = Dates.FALL;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames2 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      Currencies currencies1 = Currencies.RUB;
      Participants participants2 = Participants.MARK;
      classUnderTestApogen0.formNewEventPage(currencies1, participants0, participants2);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
      classUnderTestApogen0.cancelNewTransactionPage();
      TripNames tripNames3 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToEditEventHomePage(tripNames3);
      Participants participants3 = Participants.MATTEO;
      classUnderTestApogen0.formEditEventPage(currencies1, participants1, participants3);
  }

  //Test case number: 1
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.cancelEditEventPage()V: Line 291
   * Goal 3. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 4. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 5. main.ClassUnderTestApogen.formNewTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Participants;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 138
   * Goal 6. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 7. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 8. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 9. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 10. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 11. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.BGN;
      Participants participants0 = Participants.MARK;
      TripNames tripNames1 = TripNames.BARCELONA;
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames3 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames3);
      Participants participants2 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants2, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
      Transactions transactions0 = Transactions.SHOPPING;
      Participants participants3 = Participants.MATTEO;
      int int0 = 753;
      Price price0 = new Price(int0);
      Dates dates0 = Dates.FALL;
      classUnderTestApogen0.formNewTransactionPage(transactions0, participants3, price0, dates0);
      classUnderTestApogen0.goToEditEventHomePage(tripNames1);
      classUnderTestApogen0.cancelEditEventPage();
      classUnderTestApogen0.goToIndexPageHomePage();
  }

  //Test case number: 2
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.closeAddTransactionPage()V: Line 532
   * Goal 3. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 4. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 5. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 6. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 7. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 8. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 9. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 10. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 11. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      Currencies currencies0 = Currencies.RON;
      Participants participants0 = Participants.MIKE;
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.closeAddTransactionPage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.MUSEUM;
      int int0 = 539;
      Price price0 = new Price(int0);
      Dates dates0 = Dates.FALL;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames1);
      Participants participants2 = Participants.MATTEO;
      classUnderTestApogen0.formEditEventPage(currencies0, participants0, participants2);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames2 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
      classUnderTestApogen0.cancelNewEventPage();
  }

  //Test case number: 3
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formEditTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Participants;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 195
   * Goal 3. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 4. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 5. main.ClassUnderTestApogen.goToEditTransactionPageTransactionsPage(Lcustom_classes/Id;)V: Line 496
   * Goal 6. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 7. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 8. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 9. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 10. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 11. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames1 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames1);
      Currencies currencies0 = Currencies.HRK;
      Participants participants0 = Participants.LUKE;
      Participants participants1 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.DISCO;
      int int0 = (-1861);
      Price price0 = new Price(int0);
      Dates dates0 = Dates.SPRING;
      Transactions transactions1 = Transactions.TICKETS;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions1, price0, dates0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      int int1 = 2735;
      Id id0 = new Id(int1);
      classUnderTestApogen0.goToEditTransactionPageTransactionsPage(id0);
      Dates dates1 = Dates.SUMMER;
      classUnderTestApogen0.formEditTransactionPage(transactions0, participants1, price0, dates1);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames2 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
  }

  //Test case number: 4
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.goToConfirmDeletionPageEditEventPage()V: Line 329
   * Goal 4. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 5. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 6. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 7. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 8. main.ClassUnderTestApogen.noConfirmDeletionPage()V: Line 262
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      Currencies currencies0 = Currencies.PLN;
      Participants participants0 = Participants.JOHN;
      TripNames tripNames1 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames1);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames1);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
  }

  //Test case number: 5
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 3. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 4. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 5. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 6. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 7. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 8. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 9. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 10. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 11. main.ClassUnderTestApogen.yesConfirmationPage()V: Line 45
   */

  @Test(timeout = 1001000)
  public void test5()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      Participants participants0 = Participants.LUKE;
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames1 = TripNames.BARCELONA;
      TripNames tripNames2 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames2);
      Currencies currencies0 = Currencies.HRK;
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames1);
      Currencies currencies1 = Currencies.PLN;
      Participants participants2 = Participants.MIKE;
      Participants participants3 = Participants.LUKE;
      classUnderTestApogen0.formEditEventPage(currencies1, participants2, participants3);
      TripNames tripNames3 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToEditEventHomePage(tripNames3);
      Participants participants4 = Participants.MARCO;
      Participants participants5 = Participants.JOHN;
      classUnderTestApogen0.formEditEventPage(currencies0, participants4, participants5);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames4 = TripNames.BARCELONA;
      Participants participants6 = Participants.LUKE;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames4);
      Currencies currencies2 = Currencies.CHF;
      Participants participants7 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies2, participants7, participants6);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames5 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames5);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames6 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames6);
      classUnderTestApogen0.yesConfirmationPage();
  }

  //Test case number: 6
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 4. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 5. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 6. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 7. main.ClassUnderTestApogen.goToHomePageIndexPage(Lcustom_classes/TripNames;)V: Line 404
   * Goal 8. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 9. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 10. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 11. main.ClassUnderTestApogen.noConfirmationPage()V: Line 30
   * Goal 12. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test6()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.HRK;
      Participants participants0 = Participants.MARK;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants0);
      } catch(RuntimeException e) {
         //
         // form: the two participants must be different Mark Mark
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToTransactionsHomePage();
      } catch(RuntimeException e) {
         //
         // goToTransactionsHomePage: expected po_apogen.HomePage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventTransactionsPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // goToEditEventTransactionsPage: expected po_apogen.TransactionsPage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      Participants participants1 = Participants.JOHN;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.formEditEventPage(currencies0, participants0, participants1);
      } catch(RuntimeException e) {
         //
         // formEditEventPage: expected po_apogen.EditEventPage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames0);
      } catch(RuntimeException e) {
         //
         // goToEditEventHomePage: expected po_apogen.HomePage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelEditEventPage();
      } catch(RuntimeException e) {
         //
         // cancelEditEventPage: expected po_apogen.EditEventPage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToIndexPageHomePage();
      } catch(RuntimeException e) {
         //
         // goToIndexPageHomePage: expected po_apogen.HomePage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames1 = TripNames.BARCELONA;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames1);
      } catch(RuntimeException e) {
         //
         // goToNewEventHomeIndexPage: expected po_apogen.IndexPage, found NewEventPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      Currencies currencies1 = Currencies.USD;
      Participants participants2 = Participants.MIKE;
      Participants participants3 = Participants.MARCO;
      classUnderTestApogen0.formNewEventPage(currencies1, participants2, participants3);
      TripNames tripNames2 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToEditEventHomePage(tripNames2);
      Participants participants4 = Participants.MATTEO;
      Participants participants5 = Participants.MIKE;
      classUnderTestApogen0.formEditEventPage(currencies0, participants4, participants5);
      TripNames tripNames3 = TripNames.BARCELONA;
      classUnderTestApogen0.goToEditEventHomePage(tripNames3);
      Participants participants6 = Participants.MATTEO;
      classUnderTestApogen0.formEditEventPage(currencies0, participants6, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.TICKETS;
      int int0 = (-407);
      Price price0 = new Price(int0);
      Dates dates0 = Dates.SUMMER;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames3);
      classUnderTestApogen0.noConfirmationPage();
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToHomePageIndexPage(tripNames1);
      } catch(IllegalStateException e) {
         //
         // HomePage not loaded properly
         //
         //verifyException("po_apogen.HomePage", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames2);
      } catch(RuntimeException e) {
         //
         // goToEditEventHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      Currencies currencies2 = Currencies.RON;
      Participants participants7 = Participants.LUKE;
      Participants participants8 = Participants.MATTEO;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.formEditEventPage(currencies2, participants7, participants8);
      } catch(RuntimeException e) {
         //
         // formEditEventPage: expected po_apogen.EditEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToTransactionsHomePage();
      } catch(RuntimeException e) {
         //
         // goToTransactionsHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      Id id0 = new Id(int0);
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditTransactionPageTransactionsPage(id0);
      } catch(RuntimeException e) {
         //
         // goToEditTransactionPageTransactionsPage: expected po_apogen.TransactionsPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.deleteEditTransactionPage();
      } catch(RuntimeException e) {
         //
         // deleteEditTransactionPage: expected po_apogen.EditTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.yesConfirmationTransactionPage();
      } catch(RuntimeException e) {
         //
         // yesConfirmationTransactionPage: expected po_apogen.ConfirmationTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
  }

  //Test case number: 7
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 2. main.ClassUnderTestApogen.goToConfirmDeletionPageEditEventPage()V: Line 329
   * Goal 3. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 4. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 5. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 6. main.ClassUnderTestApogen.yesConfirmDeletionPage()V: Line 278
   */

  @Test(timeout = 1001000)
  public void test7()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.EUR;
      Participants participants0 = Participants.JOHN;
      Participants participants1 = Participants.LUKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      TripNames tripNames1 = TripNames.BARCELONA;
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames1);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.yesConfirmDeletionPage();
  }
}
