/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 11 22:36:03 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import custom_classes.Currencies;
import custom_classes.Dates;
import custom_classes.Id;
import custom_classes.Participants;
import custom_classes.Price;
import custom_classes.Transactions;
import custom_classes.TripNames;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.cancelEditEventPage()V: Line 291
   * Goal 3. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 4. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 5. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 6. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 7. main.ClassUnderTestApogen.goToConfirmDeletionPageEditEventPage()V: Line 329
   * Goal 8. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 9. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 10. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 11. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 12. main.ClassUnderTestApogen.noConfirmDeletionPage()V: Line 262
   * Goal 13. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      Currencies currencies0 = Currencies.CZK;
      Participants participants0 = Participants.MIKE;
      TripNames tripNames0 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      classUnderTestApogen0.cancelNewEventPage();
      TripNames tripNames1 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames1);
      Participants participants1 = Participants.LUKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants1, participants0);
      classUnderTestApogen0.goToHomePageHomePage();
      TripNames tripNames2 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToEditEventHomePage(tripNames2);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
      Participants participants2 = Participants.JOHN;
      classUnderTestApogen0.formEditEventPage(currencies0, participants0, participants2);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToEditEventHomePage(tripNames1);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
      classUnderTestApogen0.cancelEditEventPage();
      classUnderTestApogen0.goToEditEventHomePage(tripNames1);
      classUnderTestApogen0.cancelEditEventPage();
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.SHOPPING;
      int int0 = 3779;
      Price price0 = new Price(int0);
      Dates dates0 = Dates.SUMMER;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
  }

  //Test case number: 1
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.cancelNewTransactionPage()V: Line 119
   * Goal 3. main.ClassUnderTestApogen.closeAddTransactionPage()V: Line 532
   * Goal 4. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 5. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 6. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 7. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 8. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 9. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 10. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      Currencies currencies0 = Currencies.HRK;
      Participants participants0 = Participants.MIKE;
      Participants participants1 = Participants.MARK;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      int int0 = (-1671);
      Id id0 = new Id(int0);
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.closeAddTransactionPage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.closeAddTransactionPage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.SHOPPING;
      Price price0 = new Price(id0.value);
      Dates dates0 = Dates.FALL;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      TripNames tripNames1 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToEditEventHomePage(tripNames1);
      Currencies currencies1 = Currencies.RON;
      classUnderTestApogen0.formEditEventPage(currencies1, participants1, participants0);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
      classUnderTestApogen0.cancelNewTransactionPage();
  }

  //Test case number: 2
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTestApogen.addWithDetailsAddTransactionPage()V: Line 516
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.formNewTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Participants;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 138
   * Goal 4. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 5. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 6. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.CZK;
      Participants participants0 = Participants.LUKE;
      Participants participants1 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      int int0 = (-200);
      Price price0 = new Price(int0);
      Dates dates0 = Dates.SUMMER;
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      classUnderTestApogen0.addWithDetailsAddTransactionPage();
      Transactions transactions0 = Transactions.LUNCH;
      classUnderTestApogen0.formNewTransactionPage(transactions0, participants0, price0, dates0);
  }

  //Test case number: 3
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 2. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 3. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 4. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 5. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 6. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 7. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 8. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 9. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 10. main.ClassUnderTestApogen.noConfirmationPage()V: Line 30
   * Goal 11. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.RESTAURANT;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames0);
      Currencies currencies0 = Currencies.CHF;
      Participants participants0 = Participants.MARCO;
      int int0 = 2212;
      Price price0 = new Price(int0);
      Dates dates0 = Dates.WINTER;
      Participants participants1 = Participants.MARK;
      TripNames tripNames1 = TripNames.ROME;
      Participants participants2 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants2);
      classUnderTestApogen0.goToTransactionsHomePage();
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames2);
      Currencies currencies1 = Currencies.USD;
      Participants participants3 = Participants.MARCO;
      Participants participants4 = Participants.LUKE;
      classUnderTestApogen0.formEditEventPage(currencies1, participants3, participants4);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames3 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames3);
      Currencies currencies2 = Currencies.USD;
      Participants participants5 = Participants.JOHN;
      classUnderTestApogen0.formNewEventPage(currencies2, participants5, participants0);
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames1);
      classUnderTestApogen0.noConfirmationPage();
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames0);
      classUnderTestApogen0.formNewEventPage(currencies2, participants1, participants5);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.LUNCH;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
  }

  //Test case number: 4
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTestApogen.cancelNewEventPage()V: Line 347
   * Goal 2. main.ClassUnderTestApogen.formEditEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 309
   * Goal 3. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 4. main.ClassUnderTestApogen.goToAddTransactionPageTransactionsPage()V: Line 460
   * Goal 5. main.ClassUnderTestApogen.goToConfirmDeletionPageEditEventPage()V: Line 329
   * Goal 6. main.ClassUnderTestApogen.goToEditEventTransactionsPage(Lcustom_classes/TripNames;)V: Line 475
   * Goal 7. main.ClassUnderTestApogen.goToHomePageIndexPage(Lcustom_classes/TripNames;)V: Line 404
   * Goal 8. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 9. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 10. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 11. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 12. main.ClassUnderTestApogen.noConfirmDeletionPage()V: Line 262
   * Goal 13. main.ClassUnderTestApogen.quickAddAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 557
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToHomePageIndexPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // goToHomePage: tripName Trip to Rome does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToTransactionsHomePage();
      } catch(RuntimeException e) {
         //
         // goToTransactionsHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      int int0 = 3169;
      Id id0 = new Id(int0);
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditTransactionPageTransactionsPage(id0);
      } catch(RuntimeException e) {
         //
         // goToEditTransactionPageTransactionsPage: expected po_apogen.TransactionsPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.deleteEditTransactionPage();
      } catch(RuntimeException e) {
         //
         // deleteEditTransactionPage: expected po_apogen.EditTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationTransactionPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationTransactionPage: expected po_apogen.ConfirmationTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelEditTransactionPage();
      } catch(RuntimeException e) {
         //
         // cancelEditTransactionPage: expected po_apogen.EditTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames1 = TripNames.BARCELONA;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames1);
      } catch(RuntimeException e) {
         //
         // goToEditEventHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelEditEventPage();
      } catch(RuntimeException e) {
         //
         // cancelEditEventPage: expected po_apogen.EditEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames2);
      } catch(RuntimeException e) {
         //
         // goToEditEventHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelEditEventPage();
      } catch(RuntimeException e) {
         //
         // cancelEditEventPage: expected po_apogen.EditEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames3 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames3);
      } catch(RuntimeException e) {
         //
         // goToEditEventHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelEditEventPage();
      } catch(RuntimeException e) {
         //
         // cancelEditEventPage: expected po_apogen.EditEventPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToTransactionsHomePage();
      } catch(RuntimeException e) {
         //
         // goToTransactionsHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditTransactionPageTransactionsPage(id0);
      } catch(RuntimeException e) {
         //
         // goToEditTransactionPageTransactionsPage: expected po_apogen.TransactionsPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.cancelEditTransactionPage();
      } catch(RuntimeException e) {
         //
         // cancelEditTransactionPage: expected po_apogen.EditTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToIndexPageHomePage();
      } catch(RuntimeException e) {
         //
         // goToIndexPageHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames3);
      classUnderTestApogen0.cancelNewEventPage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames3);
      classUnderTestApogen0.cancelNewEventPage();
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames1);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Trip To Barcelona does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.yesConfirmationPage();
      } catch(RuntimeException e) {
         //
         // yesConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames4 = TripNames.BARCELONA;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToConfirmationIndexPage(tripNames4);
      } catch(RuntimeException e) {
         //
         // goToConfirmation: tripName Trip To Barcelona does not exist
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.noConfirmationPage();
      } catch(RuntimeException e) {
         //
         // noConfirmationPage: expected po_apogen.ConfirmationPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      TripNames tripNames5 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames5);
      Currencies currencies0 = Currencies.HRK;
      Participants participants0 = Participants.MATTEO;
      Participants participants1 = Participants.LUKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToEditEventTransactionsPage(tripNames4);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.noConfirmDeletionPage();
      Participants participants2 = Participants.MARCO;
      classUnderTestApogen0.formEditEventPage(currencies0, participants2, participants0);
      TripNames tripNames6 = TripNames.BARCELONA;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToEditEventHomePage(tripNames6);
      } catch(RuntimeException e) {
         //
         // goToEditEvent: new trip name Trip To Barcelona already exists
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      Participants participants3 = Participants.MATTEO;
      Participants participants4 = Participants.MIKE;
      // Undeclared exception!
      try { 
        classUnderTestApogen0.formEditEventPage(currencies0, participants3, participants4);
      } catch(RuntimeException e) {
         //
         // formEditEventPage: expected po_apogen.EditEventPage, found HomePage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      classUnderTestApogen0.goToTransactionsHomePage();
      classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      Transactions transactions0 = Transactions.DISCO;
      int int1 = (-1587);
      Price price0 = new Price(int1);
      Dates dates0 = Dates.SPRING;
      classUnderTestApogen0.quickAddAddTransactionPage(transactions0, price0, dates0);
      classUnderTestApogen0.goToIndexPageHomePage();
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToHomePageIndexPage(tripNames1);
      } catch(IllegalStateException e) {
         //
         // HomePage not loaded properly
         //
         //verifyException("po_apogen.HomePage", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToTransactionsHomePage();
      } catch(RuntimeException e) {
         //
         // goToTransactionsHomePage: expected po_apogen.HomePage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.goToAddTransactionPageTransactionsPage();
      } catch(RuntimeException e) {
         //
         // goToAddTransactionPageTransactionsPage: expected po_apogen.TransactionsPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTestApogen0.closeAddTransactionPage();
      } catch(RuntimeException e) {
         //
         // closeAddTransactionPage: expected po_apogen.AddTransactionPage, found IndexPage
         //
         //verifyException("main.ClassUnderTestApogen", e);
      }
  }

  //Test case number: 5
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 2. main.ClassUnderTestApogen.goToConfirmDeletionPageEditEventPage()V: Line 329
   * Goal 3. main.ClassUnderTestApogen.goToEditEventHomePage(Lcustom_classes/TripNames;)V: Line 59
   * Goal 4. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 5. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 6. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 7. main.ClassUnderTestApogen.yesConfirmDeletionPage()V: Line 278
   */

  @Test(timeout = 1001000)
  public void test5()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      TripNames tripNames0 = TripNames.RESTAURANT;
      Participants participants0 = Participants.JOHN;
      TripNames tripNames1 = TripNames.AMUSEMENT_PARK;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames1);
      Currencies currencies0 = Currencies.HRK;
      Participants participants1 = Participants.MIKE;
      classUnderTestApogen0.formNewEventPage(currencies0, participants0, participants1);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames2 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
      Currencies currencies1 = Currencies.HRK;
      Participants participants2 = Participants.MARCO;
      Participants participants3 = Participants.JOHN;
      classUnderTestApogen0.formNewEventPage(currencies1, participants2, participants3);
      classUnderTestApogen0.goToEditEventHomePage(tripNames0);
      classUnderTestApogen0.goToConfirmDeletionPageEditEventPage();
      classUnderTestApogen0.yesConfirmDeletionPage();
  }

  //Test case number: 6
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTestApogen.formNewEventPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 365
   * Goal 2. main.ClassUnderTestApogen.goToConfirmationIndexPage(Lcustom_classes/TripNames;)V: Line 385
   * Goal 3. main.ClassUnderTestApogen.goToHomePageHomePage()V: Line 77
   * Goal 4. main.ClassUnderTestApogen.goToIndexPageHomePage()V: Line 91
   * Goal 5. main.ClassUnderTestApogen.goToNewEventHomeIndexPage(Lcustom_classes/TripNames;)V: Line 423
   * Goal 6. main.ClassUnderTestApogen.goToNewEventNavbarIndexPage(Lcustom_classes/TripNames;)V: Line 442
   * Goal 7. main.ClassUnderTestApogen.goToTransactionsHomePage()V: Line 105
   * Goal 8. main.ClassUnderTestApogen.yesConfirmationPage()V: Line 45
   */

  @Test(timeout = 1001000)
  public void test6()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      Participants participants0 = Participants.JOHN;
      TripNames tripNames0 = TripNames.RESTAURANT;
      Participants participants1 = Participants.MIKE;
      TripNames tripNames1 = TripNames.RESTAURANT;
      Currencies currencies0 = Currencies.CHF;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames1);
      Currencies currencies1 = Currencies.USD;
      Participants participants2 = Participants.MIKE;
      Participants participants3 = Participants.JOHN;
      classUnderTestApogen0.formNewEventPage(currencies1, participants2, participants3);
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToConfirmationIndexPage(tripNames0);
      classUnderTestApogen0.yesConfirmationPage();
      TripNames tripNames2 = TripNames.BARCELONA;
      classUnderTestApogen0.goToNewEventHomeIndexPage(tripNames2);
      Participants participants4 = Participants.MARK;
      classUnderTestApogen0.formNewEventPage(currencies0, participants4, participants3);
      classUnderTestApogen0.goToIndexPageHomePage();
      TripNames tripNames3 = TripNames.AMUSEMENT_PARK;
      TripNames tripNames4 = TripNames.ROME;
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames4);
      Currencies currencies2 = Currencies.EUR;
      Participants participants5 = Participants.MATTEO;
      classUnderTestApogen0.formNewEventPage(currencies2, participants5, participants1);
      classUnderTestApogen0.goToIndexPageHomePage();
      classUnderTestApogen0.goToNewEventNavbarIndexPage(tripNames3);
      Currencies currencies3 = Currencies.CHF;
      Participants participants6 = Participants.MARK;
      classUnderTestApogen0.formNewEventPage(currencies3, participants6, participants0);
      classUnderTestApogen0.goToHomePageHomePage();
      classUnderTestApogen0.goToTransactionsHomePage();
  }
}
