/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 10 08:35:36 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Addresses;
import custom_classes.Cities;
import custom_classes.Dates;
import custom_classes.FirstNames;
import custom_classes.LastNames;
import custom_classes.PetNames;
import custom_classes.PetTypes;
import custom_classes.Telephones;
import custom_classes.VisitDescriptions;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTestApogen.editOwnerEditOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 297
   * Goal 2. main.ClassUnderTestApogen.formVisitsPage(Lcustom_classes/Dates;Lcustom_classes/VisitDescriptions;)V: Line 57
   * Goal 3. main.ClassUnderTestApogen.goToAddNewPetOwnerInformationPage()V: Line 114
   * Goal 4. main.ClassUnderTestApogen.goToEditOwnerOwnerInformationPage()V: Line 128
   * Goal 5. main.ClassUnderTestApogen.goToEditPetThroghEditLinkOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 145
   * Goal 6. main.ClassUnderTestApogen.goToEditPetThroughNameOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 166
   * Goal 7. main.ClassUnderTestApogen.goToIndexOwnerInformationPage()V: Line 185
   * Goal 8. main.ClassUnderTestApogen.goToIndexWelcomePage()V: Line 311
   * Goal 9. main.ClassUnderTestApogen.goToNewOwnerIndexPage()V: Line 218
   * Goal 10. main.ClassUnderTestApogen.goToOwnerInformationOwnersPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;)V: Line 74
   * Goal 11. main.ClassUnderTestApogen.goToVetsIndexPage()V: Line 246
   * Goal 12. main.ClassUnderTestApogen.goToVisitsOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 200
   * Goal 13. main.ClassUnderTestApogen.goToWelcomeIndexPage()V: Line 260
   * Goal 14. main.ClassUnderTestApogen.submitNewPetPage(Lcustom_classes/PetNames;Lcustom_classes/Dates;Lcustom_classes/PetTypes;)V: Line 42
   * Goal 15. main.ClassUnderTestApogen.submitOwnerFormNewOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 279
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToNewOwnerIndexPage();
      FirstNames firstNames0 = FirstNames.EDUARDO;
      LastNames lastNames0 = LastNames.RODRIQUEZ;
      Addresses addresses0 = Addresses.LIBERTY;
      Cities cities0 = Cities.MADISON;
      Telephones telephones0 = Telephones.PHONE3;
      classUnderTestApogen0.submitOwnerFormNewOwnerPage(firstNames0, lastNames0, addresses0, cities0, telephones0);
      FirstNames firstNames1 = FirstNames.EDUARDO;
      classUnderTestApogen0.goToOwnerInformationOwnersPage(firstNames1, lastNames0);
      PetNames petNames0 = PetNames.BASIL;
      VisitDescriptions visitDescriptions0 = VisitDescriptions.ONE;
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      PetNames petNames1 = PetNames.LEO;
      Dates dates0 = Dates.DATE3;
      PetTypes petTypes0 = PetTypes.BIRD;
      classUnderTestApogen0.submitNewPetPage(petNames1, dates0, petTypes0);
      PetNames petNames2 = PetNames.LEO;
      classUnderTestApogen0.goToEditPetThroughNameOwnerInformationPage(petNames2);
      PetNames petNames3 = PetNames.BASIL;
      classUnderTestApogen0.submitNewPetPage(petNames3, dates0, petTypes0);
      classUnderTestApogen0.goToEditOwnerOwnerInformationPage();
      FirstNames firstNames2 = FirstNames.HAROLD;
      LastNames lastNames1 = LastNames.BLACK;
      Addresses addresses1 = Addresses.FRIENDLY;
      Telephones telephones1 = Telephones.PHONE3;
      classUnderTestApogen0.editOwnerEditOwnerPage(firstNames2, lastNames1, addresses1, cities0, telephones1);
      PetNames petNames4 = PetNames.LEO;
      Dates dates1 = Dates.DATE3;
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      PetNames petNames5 = PetNames.ROSY;
      PetTypes petTypes1 = PetTypes.SNAKE;
      classUnderTestApogen0.submitNewPetPage(petNames5, dates1, petTypes1);
      PetTypes petTypes2 = PetTypes.CAT;
      classUnderTestApogen0.goToEditPetThroghEditLinkOwnerInformationPage(petNames5);
      Dates dates2 = Dates.DATE4;
      classUnderTestApogen0.submitNewPetPage(petNames5, dates2, petTypes2);
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      Dates dates3 = Dates.DATE1;
      PetTypes petTypes3 = PetTypes.LIZARD;
      classUnderTestApogen0.submitNewPetPage(petNames4, dates3, petTypes3);
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      PetNames petNames6 = PetNames.JEWEL;
      Dates dates4 = Dates.DATE4;
      classUnderTestApogen0.submitNewPetPage(petNames6, dates4, petTypes1);
      classUnderTestApogen0.goToEditOwnerOwnerInformationPage();
      FirstNames firstNames3 = FirstNames.EDUARDO;
      LastNames lastNames2 = LastNames.FRANKLIN;
      Addresses addresses2 = Addresses.LIBERTY;
      classUnderTestApogen0.editOwnerEditOwnerPage(firstNames3, lastNames2, addresses2, cities0, telephones0);
      classUnderTestApogen0.goToEditOwnerOwnerInformationPage();
      LastNames lastNames3 = LastNames.FRANKLIN;
      Addresses addresses3 = Addresses.FRIENDLY;
      Cities cities1 = Cities.MCFARLAND;
      Telephones telephones2 = Telephones.PHONE2;
      classUnderTestApogen0.editOwnerEditOwnerPage(firstNames3, lastNames3, addresses3, cities1, telephones2);
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      Dates dates5 = Dates.DATE3;
      classUnderTestApogen0.submitNewPetPage(petNames1, dates5, petTypes0);
      classUnderTestApogen0.goToVisitsOwnerInformationPage(petNames1);
      classUnderTestApogen0.formVisitsPage(dates5, visitDescriptions0);
      classUnderTestApogen0.goToVisitsOwnerInformationPage(petNames0);
      Dates dates6 = Dates.DATE3;
      VisitDescriptions visitDescriptions1 = VisitDescriptions.FOUR;
      classUnderTestApogen0.formVisitsPage(dates6, visitDescriptions1);
      classUnderTestApogen0.goToEditPetThroughNameOwnerInformationPage(petNames1);
      PetNames petNames7 = PetNames.ROSY;
      Dates dates7 = Dates.DATE4;
      classUnderTestApogen0.submitNewPetPage(petNames7, dates7, petTypes3);
      classUnderTestApogen0.goToEditOwnerOwnerInformationPage();
      Addresses addresses4 = Addresses.COMMERCE;
      Cities cities2 = Cities.MONONA;
      classUnderTestApogen0.editOwnerEditOwnerPage(firstNames3, lastNames2, addresses4, cities2, telephones2);
      classUnderTestApogen0.goToIndexOwnerInformationPage();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToIndexWelcomePage();
      classUnderTestApogen0.goToVetsIndexPage();
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * Goal 1. main.ClassUnderTestApogen.goToIndexVetsPage()V: Line 27
   * Goal 2. main.ClassUnderTestApogen.goToNewOwnerIndexPage()V: Line 218
   * Goal 3. main.ClassUnderTestApogen.goToVetsIndexPage()V: Line 246
   * Goal 4. main.ClassUnderTestApogen.searchFilterOwnersPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;)V: Line 95
   * Goal 5. main.ClassUnderTestApogen.submitOwnerFormNewOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 279
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToVetsIndexPage();
      classUnderTestApogen0.goToIndexVetsPage();
      classUnderTestApogen0.goToVetsIndexPage();
      classUnderTestApogen0.goToIndexVetsPage();
      classUnderTestApogen0.goToVetsIndexPage();
      classUnderTestApogen0.goToIndexVetsPage();
      classUnderTestApogen0.goToNewOwnerIndexPage();
      FirstNames firstNames0 = FirstNames.EDUARDO;
      LastNames lastNames0 = LastNames.DAVIS;
      Addresses addresses0 = Addresses.CARDINAL;
      Cities cities0 = Cities.WINDSOR;
      Telephones telephones0 = Telephones.PHONE3;
      classUnderTestApogen0.submitOwnerFormNewOwnerPage(firstNames0, lastNames0, addresses0, cities0, telephones0);
      classUnderTestApogen0.searchFilterOwnersPage(firstNames0, lastNames0);
  }

  //Test case number: 2
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTestApogen.editOwnerEditOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 297
   * Goal 2. main.ClassUnderTestApogen.goToAddNewPetOwnerInformationPage()V: Line 114
   * Goal 3. main.ClassUnderTestApogen.goToEditOwnerOwnerInformationPage()V: Line 128
   * Goal 4. main.ClassUnderTestApogen.goToEditPetThroughNameOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 166
   * Goal 5. main.ClassUnderTestApogen.goToIndexOwnerInformationPage()V: Line 185
   * Goal 6. main.ClassUnderTestApogen.goToNewOwnerIndexPage()V: Line 218
   * Goal 7. main.ClassUnderTestApogen.goToNewOwnerWelcomePage()V: Line 325
   * Goal 8. main.ClassUnderTestApogen.goToOwnerInformationOwnersPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;)V: Line 74
   * Goal 9. main.ClassUnderTestApogen.goToWelcomeIndexPage()V: Line 260
   * Goal 10. main.ClassUnderTestApogen.submitNewPetPage(Lcustom_classes/PetNames;Lcustom_classes/Dates;Lcustom_classes/PetTypes;)V: Line 42
   * Goal 11. main.ClassUnderTestApogen.submitOwnerFormNewOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 279
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToNewOwnerIndexPage();
      FirstNames firstNames0 = FirstNames.GEORGE;
      LastNames lastNames0 = LastNames.RODRIQUEZ;
      Addresses addresses0 = Addresses.CARDINAL;
      Cities cities0 = Cities.MCFARLAND;
      Telephones telephones0 = Telephones.PHONE3;
      classUnderTestApogen0.submitOwnerFormNewOwnerPage(firstNames0, lastNames0, addresses0, cities0, telephones0);
      LastNames lastNames1 = LastNames.FRANKLIN;
      FirstNames firstNames1 = FirstNames.GEORGE;
      LastNames lastNames2 = LastNames.RODRIQUEZ;
      classUnderTestApogen0.goToOwnerInformationOwnersPage(firstNames1, lastNames2);
      PetNames petNames0 = PetNames.LEO;
      Dates dates0 = Dates.DATE4;
      PetTypes petTypes0 = PetTypes.DOG;
      classUnderTestApogen0.goToEditOwnerOwnerInformationPage();
      FirstNames firstNames2 = FirstNames.HAROLD;
      Cities cities1 = Cities.MCFARLAND;
      Telephones telephones1 = Telephones.PHONE4;
      classUnderTestApogen0.editOwnerEditOwnerPage(firstNames2, lastNames1, addresses0, cities1, telephones1);
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      PetNames petNames1 = PetNames.LEO;
      classUnderTestApogen0.submitNewPetPage(petNames1, dates0, petTypes0);
      classUnderTestApogen0.goToEditPetThroughNameOwnerInformationPage(petNames0);
      PetNames petNames2 = PetNames.JEWEL;
      Dates dates1 = Dates.DATE4;
      classUnderTestApogen0.submitNewPetPage(petNames2, dates1, petTypes0);
      classUnderTestApogen0.goToIndexOwnerInformationPage();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToNewOwnerWelcomePage();
      LastNames lastNames3 = LastNames.RODRIQUEZ;
      Addresses addresses1 = Addresses.LIBERTY;
      Telephones telephones2 = Telephones.PHONE4;
      classUnderTestApogen0.submitOwnerFormNewOwnerPage(firstNames2, lastNames3, addresses1, cities1, telephones2);
  }

  //Test case number: 3
  /*
   * 3 covered goals:
   * Goal 1. main.ClassUnderTestApogen.goToIndexWelcomePage()V: Line 311
   * Goal 2. main.ClassUnderTestApogen.goToOwnersIndexPage()V: Line 232
   * Goal 3. main.ClassUnderTestApogen.goToWelcomeIndexPage()V: Line 260
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToIndexWelcomePage();
      classUnderTestApogen0.goToOwnersIndexPage();
  }

  //Test case number: 4
  /*
   * 4 covered goals:
   * Goal 1. main.ClassUnderTestApogen.goToIndexVetsPage()V: Line 27
   * Goal 2. main.ClassUnderTestApogen.goToOwnersWelcomePage()V: Line 339
   * Goal 3. main.ClassUnderTestApogen.goToVetsIndexPage()V: Line 246
   * Goal 4. main.ClassUnderTestApogen.goToWelcomeIndexPage()V: Line 260
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToVetsIndexPage();
      classUnderTestApogen0.goToIndexVetsPage();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToOwnersWelcomePage();
  }
}
