/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 19 08:44:23 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import custom_classes.Currencies;
import custom_classes.Dates;
import custom_classes.Id;
import custom_classes.Participants;
import custom_classes.Price;
import custom_classes.Transactions;
import custom_classes.TripNames;
import main.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTest.addParticipantAddEditEventContainerPage(Lcustom_classes/Participants;)V: Line 450
   * Goal 2. main.ClassUnderTest.closeShareEventPage()V: Line 584
   * Goal 3. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 4. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 5. main.ClassUnderTest.editEventEventDetailsContainerPage(Lcustom_classes/TripNames;)V: Line 281
   * Goal 6. main.ClassUnderTest.goToOverviewEventDetailsContainerPage()V: Line 335
   * Goal 7. main.ClassUnderTest.shareEventEventDetailsContainerPage()V: Line 385
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      Currencies currencies0 = Currencies.CZK;
      Participants participants0 = Participants.LUKE;
      Participants participants1 = Participants.MARCO;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants1);
      classUnderTest0.shareEventEventDetailsContainerPage();
      classUnderTest0.closeShareEventPage();
      classUnderTest0.goToOverviewEventDetailsContainerPage();
      TripNames tripNames1 = TripNames.RESTAURANT;
      classUnderTest0.editEventEventDetailsContainerPage(tripNames1);
      Participants participants2 = Participants.MATTEO;
      classUnderTest0.addParticipantAddEditEventContainerPage(participants2);
      classUnderTest0.shareEventEventDetailsContainerPage();
      classUnderTest0.closeShareEventPage();
  }

  //Test case number: 1
  /*
   * 5 covered goals:
   * Goal 1. main.ClassUnderTest.addQuickAddTransactionPage(Lcustom_classes/Transactions;Lcustom_classes/Price;Lcustom_classes/Dates;)V: Line 610
   * Goal 2. main.ClassUnderTest.addTransactionEventDetailsContainerPage()V: Line 263
   * Goal 3. main.ClassUnderTest.closeQuickAddTransactionPage()V: Line 646
   * Goal 4. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 5. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      Currencies currencies0 = Currencies.BGN;
      Participants participants0 = Participants.MATTEO;
      Participants participants1 = Participants.MARK;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants1);
      int int0 = (-390);
      Id id0 = new Id(int0);
      classUnderTest0.addTransactionEventDetailsContainerPage();
      classUnderTest0.closeQuickAddTransactionPage();
      classUnderTest0.addTransactionEventDetailsContainerPage();
      Transactions transactions0 = Transactions.LUNCH;
      Price price0 = new Price(id0.value);
      Dates dates0 = Dates.FALL;
      classUnderTest0.addQuickAddTransactionPage(transactions0, price0, dates0);
  }

  //Test case number: 2
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.cancelAddEditEventContainerPage()V: Line 470
   * Goal 2. main.ClassUnderTest.cancelAddEditEventContainerPage()V: Line 474
   * Goal 3. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 4. main.ClassUnderTest.createNewEventHomeHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 31
   * Goal 5. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 6. main.ClassUnderTest.editEventEventDetailsContainerPage(Lcustom_classes/TripNames;)V: Line 281
   * Goal 7. main.ClassUnderTest.goToAboutHomePageContainerPage()V: Line 93
   * Goal 8. main.ClassUnderTest.goToFeaturesHomePageContainerPage()V: Line 126
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToAboutHomePageContainerPage();
      TripNames tripNames0 = TripNames.ROME;
      classUnderTest0.goToAboutHomePageContainerPage();
      classUnderTest0.goToFeaturesHomePageContainerPage();
      TripNames tripNames1 = TripNames.RESTAURANT;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames1);
      Currencies currencies0 = Currencies.USD;
      Participants participants0 = Participants.MATTEO;
      classUnderTest0.cancelAddEditEventContainerPage();
      classUnderTest0.goToAboutHomePageContainerPage();
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames2);
      Participants participants1 = Participants.MARCO;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants1);
      classUnderTest0.editEventEventDetailsContainerPage(tripNames0);
      classUnderTest0.cancelAddEditEventContainerPage();
  }

  //Test case number: 3
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.cancelConfirmationPage()V: Line 163
   * Goal 2. main.ClassUnderTest.closeShareEventPage()V: Line 584
   * Goal 3. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 4. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 5. main.ClassUnderTest.deleteEventAddEditEventContainerPage()V: Line 523
   * Goal 6. main.ClassUnderTest.editEventEventDetailsContainerPage(Lcustom_classes/TripNames;)V: Line 281
   * Goal 7. main.ClassUnderTest.goToAboutHomePageContainerPage()V: Line 93
   * Goal 8. main.ClassUnderTest.goToFeaturesHomePageContainerPage()V: Line 126
   * Goal 9. main.ClassUnderTest.goToOverviewEventDetailsContainerPage()V: Line 335
   * Goal 10. main.ClassUnderTest.shareEventEventDetailsContainerPage()V: Line 385
   * Goal 11. main.ClassUnderTest.viewDetailsAsEventDetailsContainerPage(Lcustom_classes/Participants;)V: Line 401
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToAboutHomePageContainerPage();
      classUnderTest0.goToFeaturesHomePageContainerPage();
      TripNames tripNames0 = TripNames.RESTAURANT;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      Participants participants0 = Participants.MIKE;
      Currencies currencies0 = Currencies.CHF;
      Participants participants1 = Participants.MATTEO;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants1, participants0);
      classUnderTest0.goToOverviewEventDetailsContainerPage();
      classUnderTest0.viewDetailsAsEventDetailsContainerPage(participants0);
      classUnderTest0.shareEventEventDetailsContainerPage();
      classUnderTest0.closeShareEventPage();
      classUnderTest0.shareEventEventDetailsContainerPage();
      classUnderTest0.closeShareEventPage();
      classUnderTest0.shareEventEventDetailsContainerPage();
      classUnderTest0.closeShareEventPage();
      classUnderTest0.shareEventEventDetailsContainerPage();
      classUnderTest0.closeShareEventPage();
      classUnderTest0.goToOverviewEventDetailsContainerPage();
      TripNames tripNames1 = TripNames.AMUSEMENT_PARK;
      classUnderTest0.editEventEventDetailsContainerPage(tripNames1);
      classUnderTest0.deleteEventAddEditEventContainerPage();
      classUnderTest0.cancelConfirmationPage();
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTest.cancelConfirmationPage()V: Line 175
   * Goal 2. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 3. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 4. main.ClassUnderTest.deleteEventHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 75
   * Goal 5. main.ClassUnderTest.goToHomeEventDetailsContainerPage()V: Line 321
   * Goal 6. main.ClassUnderTest.goToOverviewEventDetailsContainerPage()V: Line 335
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      TripNames tripNames0 = TripNames.BARCELONA;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      Participants participants0 = Participants.MIKE;
      Currencies currencies0 = Currencies.GBP;
      Participants participants1 = Participants.MARK;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants1, participants0);
      classUnderTest0.goToOverviewEventDetailsContainerPage();
      classUnderTest0.goToHomeEventDetailsContainerPage();
      TripNames tripNames1 = TripNames.BARCELONA;
      classUnderTest0.deleteEventHomePageContainerPage(tripNames1);
      classUnderTest0.cancelConfirmationPage();
  }

  //Test case number: 5
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addTransactionEventDetailsContainerPage()V: Line 263
   * Goal 2. main.ClassUnderTest.addWithDetailsQuickAddTransactionPage()V: Line 630
   * Goal 3. main.ClassUnderTest.cancelAddEditEventContainerPage()V: Line 474
   * Goal 4. main.ClassUnderTest.cancelAddEditTransactionContainerPage()V: Line 688
   * Goal 5. main.ClassUnderTest.confirmConfirmationPage()V: Line 203
   * Goal 6. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 7. main.ClassUnderTest.createNewEventHomeHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 31
   * Goal 8. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 9. main.ClassUnderTest.deleteEventAddEditEventContainerPage()V: Line 523
   * Goal 10. main.ClassUnderTest.editEventEventDetailsContainerPage(Lcustom_classes/TripNames;)V: Line 281
   * Goal 11. main.ClassUnderTest.goToHomePageAddEditEventContainerPage()V: Line 568
   */

  @Test(timeout = 1001000)
  public void test5()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      TripNames tripNames0 = TripNames.RESTAURANT;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      Currencies currencies0 = Currencies.CZK;
      Participants participants0 = Participants.MARCO;
      Participants participants1 = Participants.JOHN;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants1);
      classUnderTest0.addTransactionEventDetailsContainerPage();
      classUnderTest0.addWithDetailsQuickAddTransactionPage();
      classUnderTest0.cancelAddEditTransactionContainerPage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTest0.editEventEventDetailsContainerPage(tripNames1);
      classUnderTest0.deleteEventAddEditEventContainerPage();
      classUnderTest0.confirmConfirmationPage();
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames2);
      classUnderTest0.goToHomePageAddEditEventContainerPage();
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      classUnderTest0.cancelAddEditEventContainerPage();
      TripNames tripNames3 = TripNames.AMUSEMENT_PARK;
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames3);
      classUnderTest0.goToHomePageAddEditEventContainerPage();
      TripNames tripNames4 = TripNames.ROME;
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames4);
  }

  //Test case number: 6
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.cancelAddEditEventContainerPage()V: Line 474
   * Goal 2. main.ClassUnderTest.confirmConfirmationPage()V: Line 215
   * Goal 3. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 4. main.ClassUnderTest.createNewEventHomeHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 31
   * Goal 5. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 6. main.ClassUnderTest.deleteEventHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 75
   * Goal 7. main.ClassUnderTest.goToAboutHomePageContainerPage()V: Line 93
   * Goal 8. main.ClassUnderTest.goToFeaturesHomePageContainerPage()V: Line 126
   * Goal 9. main.ClassUnderTest.goToHomeEventDetailsContainerPage()V: Line 321
   */

  @Test(timeout = 1001000)
  public void test6()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToFeaturesHomePageContainerPage();
      TripNames tripNames0 = TripNames.RESTAURANT;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      classUnderTest0.cancelAddEditEventContainerPage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames1);
      Currencies currencies0 = Currencies.USD;
      Participants participants0 = Participants.LUKE;
      Participants participants1 = Participants.MATTEO;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants1);
      classUnderTest0.goToHomeEventDetailsContainerPage();
      classUnderTest0.deleteEventHomePageContainerPage(tripNames1);
      classUnderTest0.confirmConfirmationPage();
      classUnderTest0.goToAboutHomePageContainerPage();
      classUnderTest0.goToFeaturesHomePageContainerPage();
      classUnderTest0.goToFeaturesHomePageContainerPage();
  }

  //Test case number: 7
  /*
   * 5 covered goals:
   * Goal 1. main.ClassUnderTest.addNewEventEventDetailsContainerPage(Lcustom_classes/TripNames;)V: Line 244
   * Goal 2. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 3. main.ClassUnderTest.createNewEventHomeHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 31
   * Goal 4. main.ClassUnderTest.goToFeaturesHomePageContainerPage()V: Line 126
   * Goal 5. main.ClassUnderTest.goToTransactionEventDetailsContainerPage()V: Line 349
   */

  @Test(timeout = 1001000)
  public void test7()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToFeaturesHomePageContainerPage();
      TripNames tripNames0 = TripNames.AMUSEMENT_PARK;
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames0);
      Currencies currencies0 = Currencies.BGN;
      Participants participants0 = Participants.MARCO;
      Participants participants1 = Participants.JOHN;
      classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants1);
      classUnderTest0.goToTransactionEventDetailsContainerPage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTest0.addNewEventEventDetailsContainerPage(tripNames1);
  }

  //Test case number: 8
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addTransactionEventDetailsContainerPage()V: Line 263
   * Goal 2. main.ClassUnderTest.addWithDetailsQuickAddTransactionPage()V: Line 630
   * Goal 3. main.ClassUnderTest.cancelAddEditEventContainerPage()V: Line 474
   * Goal 4. main.ClassUnderTest.createEventAddEditEventContainerPage(Lcustom_classes/Currencies;Lcustom_classes/Participants;Lcustom_classes/Participants;)V: Line 502
   * Goal 5. main.ClassUnderTest.createNewEventHomeHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 31
   * Goal 6. main.ClassUnderTest.createNewEventNavbarHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 53
   * Goal 7. main.ClassUnderTest.goToEventsHomePageContainerPage()V: Line 108
   * Goal 8. main.ClassUnderTest.goToFeaturesHomePageContainerPage()V: Line 126
   * Goal 9. main.ClassUnderTest.goToHomeAddEditTransactionContainerPage()V: Line 722
   * Goal 10. main.ClassUnderTest.goToHomePageAddEditEventContainerPage()V: Line 568
   * Goal 11. main.ClassUnderTest.seeEventDetailsHomePageContainerPage(Lcustom_classes/TripNames;)V: Line 142
   */

  @Test(timeout = 1001000)
  public void test8()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      TripNames tripNames0 = TripNames.BARCELONA;
      classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames0);
      Currencies currencies0 = Currencies.RUB;
      Participants participants0 = Participants.LUKE;
      // Undeclared exception!
      try { 
        classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants0, participants0);
      } catch(RuntimeException e) {
         //
         // createEvent: the two participants must be different Luke Luke
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      int int0 = 68;
      Id id0 = new Id(int0);
      // Undeclared exception!
      try { 
        classUnderTest0.editTransactionEventDetailsContainerPage(id0);
      } catch(RuntimeException e) {
         //
         // editTransactionEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.goToHomeAddEditTransactionContainerPage();
      } catch(RuntimeException e) {
         //
         // goToHomeAddEditTransactionContainerPage: expected po.event.pages.AddEditTransactionContainerPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.goToAboutHomePageContainerPage();
      } catch(RuntimeException e) {
         //
         // goToAboutHomePageContainerPage: expected po.home.pages.HomePageContainerPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // createNewEventHomeHomePageContainerPage: expected po.home.pages.HomePageContainerPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      classUnderTest0.goToHomePageAddEditEventContainerPage();
      TripNames tripNames1 = TripNames.ROME;
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames1);
      // Undeclared exception!
      try { 
        classUnderTest0.deleteEventAddEditEventContainerPage();
      } catch(RuntimeException e) {
         //
         // deleteEvent: is not edit
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      classUnderTest0.cancelAddEditEventContainerPage();
      // Undeclared exception!
      try { 
        classUnderTest0.goToEventsHomePageContainerPage();
      } catch(RuntimeException e) {
         //
         // goToEvents: events are not present
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.goToEventsHomePageContainerPage();
      } catch(RuntimeException e) {
         //
         // goToEvents: events are not present
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.deleteEventHomePageContainerPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // deleteEvent: tripName Trip To Barcelona does not exist
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      classUnderTest0.createNewEventHomeHomePageContainerPage(tripNames1);
      Participants participants1 = Participants.LUKE;
      // Undeclared exception!
      try { 
        classUnderTest0.createEventAddEditEventContainerPage(currencies0, participants1, participants0);
      } catch(RuntimeException e) {
         //
         // createEvent: the two participants must be different Luke Luke
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      TripNames tripNames2 = TripNames.AMUSEMENT_PARK;
      // Undeclared exception!
      try { 
        classUnderTest0.addNewEventEventDetailsContainerPage(tripNames2);
      } catch(RuntimeException e) {
         //
         // addNewEventEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.deleteParticipantAddEditEventContainerPage(participants0);
      } catch(RuntimeException e) {
         //
         // deleteParticipant: is not edit or participant Luke not present or button disabled
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.editEventEventDetailsContainerPage(tripNames0);
      } catch(RuntimeException e) {
         //
         // editEventEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found AddEditEventContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      Currencies currencies1 = Currencies.RUB;
      Participants participants2 = Participants.MATTEO;
      Participants participants3 = Participants.MARCO;
      classUnderTest0.createEventAddEditEventContainerPage(currencies1, participants3, participants2);
      classUnderTest0.addTransactionEventDetailsContainerPage();
      classUnderTest0.addWithDetailsQuickAddTransactionPage();
      classUnderTest0.goToHomeAddEditTransactionContainerPage();
      classUnderTest0.goToFeaturesHomePageContainerPage();
      classUnderTest0.goToEventsHomePageContainerPage();
      classUnderTest0.goToEventsHomePageContainerPage();
      // Undeclared exception!
      try { 
        classUnderTest0.seeEventDetailsHomePageContainerPage(tripNames1);
      } catch(IllegalStateException e) {
         //
         // EventDetailsContainerPage not loaded properly
         //
         //verifyException("po.event.pages.EventDetailsContainerPage", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.addNewEventEventDetailsContainerPage(tripNames1);
      } catch(RuntimeException e) {
         //
         // addNewEventEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelAddEditEventContainerPage();
      } catch(RuntimeException e) {
         //
         // cancelAddEditEventContainerPage: expected po.event.pages.AddEditEventContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.settleUpEventDetailsContainerPage(id0);
      } catch(RuntimeException e) {
         //
         // settleUpEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.goToHomeAddEditTransactionContainerPage();
      } catch(RuntimeException e) {
         //
         // goToHomeAddEditTransactionContainerPage: expected po.event.pages.AddEditTransactionContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.goToFeaturesHomePageContainerPage();
      } catch(RuntimeException e) {
         //
         // Expected condition failed: waiting for presence of element located by: By.xpath: //div[@id=\"navbar-right\"]//a[@title=\"Features\"] (tried for 5 second(s) with 50 MILLISECONDS interval)
         //
         //verifyException("org.openqa.selenium.support.ui.WebDriverWait", e);
      }
      
      TripNames tripNames3 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTest0.deleteEventHomePageContainerPage(tripNames3);
      } catch(RuntimeException e) {
         //
         // deleteEvent: tripName Trip to Rome does not exist
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.deleteTransactionAddEditTransactionContainerPage();
      } catch(RuntimeException e) {
         //
         // deleteTransactionAddEditTransactionContainerPage: expected po.event.pages.AddEditTransactionContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      TripNames tripNames4 = TripNames.ROME;
      // Undeclared exception!
      try { 
        classUnderTest0.createNewEventNavbarHomePageContainerPage(tripNames4);
      } catch(RuntimeException e) {
         //
         // Expected condition failed: waiting for presence of element located by: By.xpath: //div[@id=\"navbar-right\"]//a[@title=\"Create New Event\"] (tried for 5 second(s) with 50 MILLISECONDS interval)
         //
         //verifyException("org.openqa.selenium.support.ui.WebDriverWait", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.deleteEventAddEditEventContainerPage();
      } catch(RuntimeException e) {
         //
         // deleteEventAddEditEventContainerPage: expected po.event.pages.AddEditEventContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      Participants participants4 = Participants.MATTEO;
      // Undeclared exception!
      try { 
        classUnderTest0.deleteParticipantAddEditEventContainerPage(participants4);
      } catch(RuntimeException e) {
         //
         // deleteParticipantAddEditEventContainerPage: expected po.event.pages.AddEditEventContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.editEventEventDetailsContainerPage(tripNames1);
      } catch(RuntimeException e) {
         //
         // editEventEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.deleteEventAddEditEventContainerPage();
      } catch(RuntimeException e) {
         //
         // deleteEventAddEditEventContainerPage: expected po.event.pages.AddEditEventContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.confirmConfirmationPage();
      } catch(RuntimeException e) {
         //
         // confirmConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.addTransactionEventDetailsContainerPage();
      } catch(RuntimeException e) {
         //
         // addTransactionEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.addWithDetailsQuickAddTransactionPage();
      } catch(RuntimeException e) {
         //
         // addWithDetailsQuickAddTransactionPage: expected po.event.pages.modals.QuickAddTransactionPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.goToHomeAddEditTransactionContainerPage();
      } catch(RuntimeException e) {
         //
         // goToHomeAddEditTransactionContainerPage: expected po.event.pages.AddEditTransactionContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.seeEventDetailsHomePageContainerPage(tripNames4);
      } catch(RuntimeException e) {
         //
         // seeEventDetails: tripName Trip to Rome does not exist
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.editEventEventDetailsContainerPage(tripNames2);
      } catch(RuntimeException e) {
         //
         // editEventEventDetailsContainerPage: expected po.event.pages.EventDetailsContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.deleteEventAddEditEventContainerPage();
      } catch(RuntimeException e) {
         //
         // deleteEventAddEditEventContainerPage: expected po.event.pages.AddEditEventContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      // Undeclared exception!
      try { 
        classUnderTest0.cancelConfirmationPage();
      } catch(RuntimeException e) {
         //
         // cancelConfirmationPage: expected po.shared.pages.ConfirmationPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
      
      Currencies currencies2 = Currencies.RUB;
      Participants participants5 = Participants.JOHN;
      // Undeclared exception!
      try { 
        classUnderTest0.createEventAddEditEventContainerPage(currencies2, participants5, participants3);
      } catch(RuntimeException e) {
         //
         // createEventAddEditEventContainerPage: expected po.event.pages.AddEditEventContainerPage, found HomePageContainerPage
         //
         //verifyException("main.ClassUnderTest", e);
      }
  }
}
