/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 14 13:27:52 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.BoardNames;
import custom_classes.CardComment;
import custom_classes.CardDescription;
import custom_classes.CardTag;
import custom_classes.CardText;
import custom_classes.Email;
import custom_classes.Id;
import custom_classes.ListNames;
import custom_classes.Passwords;
import custom_classes.PeopleNames;
import main.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 20 covered goals:
   * Goal 1. main.ClassUnderTest.addCommentCardDetails(Lcustom_classes/CardComment;)V: Line 412
   * Goal 2. main.ClassUnderTest.addNewBoardBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 29
   * Goal 3. main.ClassUnderTest.addNewCardToListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/CardText;)V: Line 149
   * Goal 4. main.ClassUnderTest.addNewListBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 169
   * Goal 5. main.ClassUnderTest.addNewMemberToCurrentBoardBoardListContainerPage(Lcustom_classes/Email;)V: Line 194
   * Goal 6. main.ClassUnderTest.goToBoardListBoardsContainerPage()V: Line 63
   * Goal 7. main.ClassUnderTest.goToBoardUsingNavbarBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 79
   * Goal 8. main.ClassUnderTest.goToCardOfListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/Id;)V: Line 256
   * Goal 9. main.ClassUnderTest.goToSignInPageSignUpContainerPage()V: Line 642
   * Goal 10. main.ClassUnderTest.goToSignUpLoginContainerPage()V: Line 587
   * Goal 11. main.ClassUnderTest.loginAsJohnLoginContainerPage()V: Line 601
   * Goal 12. main.ClassUnderTest.loginLoginContainerPage(Lcustom_classes/Email;Lcustom_classes/Passwords;)V: Line 627
   * Goal 13. main.ClassUnderTest.openAddNewBoardFormBoardsContainerPage()V: Line 98
   * Goal 14. main.ClassUnderTest.openAddNewListFormBoardListContainerPage()V: Line 276
   * Goal 15. main.ClassUnderTest.openAddNewMemberFormBoardListContainerPage()V: Line 292
   * Goal 16. main.ClassUnderTest.openNewCardToListFormBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 313
   * Goal 17. main.ClassUnderTest.openUpdateListFormBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 334
   * Goal 18. main.ClassUnderTest.signOutBoardListContainerPage()V: Line 352
   * Goal 19. main.ClassUnderTest.updateListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/ListNames;)V: Line 372
   * Goal 20. main.ClassUnderTest.viewAllBoardsBoardsContainerPage()V: Line 127
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      Email email0 = Email.JOHNDOE;
      Passwords passwords0 = Passwords.JOHNDOE;
      classUnderTest0.loginLoginContainerPage(email0, passwords0);
      BoardNames boardNames0 = BoardNames.WORK_BOARD;
      ListNames listNames0 = ListNames.PERSONAL_LIST;
      Email email1 = Email.ASD;
      BoardNames boardNames1 = BoardNames.WORK_BOARD;
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames1);
      int int0 = (-1317);
      Id id0 = new Id(int0);
      CardText cardText0 = CardText.LAUNDRY;
      classUnderTest0.addNewListBoardListContainerPage(listNames0);
      classUnderTest0.openUpdateListFormBoardListContainerPage(listNames0);
      ListNames listNames1 = ListNames.PERSONAL_LIST;
      classUnderTest0.openUpdateListFormBoardListContainerPage(listNames1);
      ListNames listNames2 = ListNames.PERSONAL_LIST;
      classUnderTest0.addNewCardToListBoardListContainerPage(listNames2, cardText0);
      classUnderTest0.openAddNewListFormBoardListContainerPage();
      classUnderTest0.addNewListBoardListContainerPage(listNames2);
      classUnderTest0.signOutBoardListContainerPage();
      classUnderTest0.goToSignUpLoginContainerPage();
      classUnderTest0.goToSignInPageSignUpContainerPage();
      classUnderTest0.loginAsJohnLoginContainerPage();
      classUnderTest0.goToBoardListBoardsContainerPage();
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      classUnderTest0.viewAllBoardsBoardsContainerPage();
      classUnderTest0.viewAllBoardsBoardsContainerPage();
      classUnderTest0.goToBoardListBoardsContainerPage();
      classUnderTest0.goToBoardUsingNavbarBoardsContainerPage(boardNames0);
      classUnderTest0.addNewMemberToCurrentBoardBoardListContainerPage(email1);
      ListNames listNames3 = ListNames.ANOTHER_LIST;
      classUnderTest0.updateListBoardListContainerPage(listNames1, listNames3);
      ListNames listNames4 = ListNames.ANOTHER_LIST;
      classUnderTest0.openNewCardToListFormBoardListContainerPage(listNames4);
      classUnderTest0.openNewCardToListFormBoardListContainerPage(listNames3);
      classUnderTest0.openAddNewMemberFormBoardListContainerPage();
      classUnderTest0.openUpdateListFormBoardListContainerPage(listNames0);
      classUnderTest0.goToCardOfListBoardListContainerPage(listNames4, id0);
      CardComment cardComment0 = CardComment.LAUNDRY;
      classUnderTest0.addCommentCardDetails(cardComment0);
  }

  //Test case number: 1
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addNewBoardBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 29
   * Goal 2. main.ClassUnderTest.addNewCardToListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/CardText;)V: Line 149
   * Goal 3. main.ClassUnderTest.addNewListBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 169
   * Goal 4. main.ClassUnderTest.addNewMemberToCurrentBoardBoardListContainerPage(Lcustom_classes/Email;)V: Line 194
   * Goal 5. main.ClassUnderTest.addNewMemberToCurrentBoardBoardListContainerPage(Lcustom_classes/Email;)V: Line 197
   * Goal 6. main.ClassUnderTest.deleteCardCardDetails()V: Line 486
   * Goal 7. main.ClassUnderTest.goToBoardListBoardListContainerPage()V: Line 216
   * Goal 8. main.ClassUnderTest.goToCardOfListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/Id;)V: Line 256
   * Goal 9. main.ClassUnderTest.loginAsJohnLoginContainerPage()V: Line 601
   * Goal 10. main.ClassUnderTest.loginLoginContainerPage(Lcustom_classes/Email;Lcustom_classes/Passwords;)V: Line 624
   * Goal 11. main.ClassUnderTest.openAddNewBoardFormBoardsContainerPage()V: Line 98
   * Goal 12. main.ClassUnderTest.updateListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/ListNames;)V: Line 372
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      Email email0 = Email.ASD;
      Passwords passwords0 = Passwords.ASD;
      classUnderTest0.loginLoginContainerPage(email0, passwords0);
      classUnderTest0.loginAsJohnLoginContainerPage();
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      BoardNames boardNames0 = BoardNames.ANOTHER_BOARD;
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      classUnderTest0.addNewMemberToCurrentBoardBoardListContainerPage(email0);
      ListNames listNames0 = ListNames.WORK_LIST;
      int int0 = 1182;
      Id id0 = new Id(int0);
      CardText cardText0 = CardText.PERSONAL;
      classUnderTest0.addNewListBoardListContainerPage(listNames0);
      ListNames listNames1 = ListNames.ANOTHER_LIST;
      classUnderTest0.addNewCardToListBoardListContainerPage(listNames0, cardText0);
      classUnderTest0.goToCardOfListBoardListContainerPage(listNames0, id0);
      classUnderTest0.deleteCardCardDetails();
      Email email1 = Email.ASD;
      classUnderTest0.addNewMemberToCurrentBoardBoardListContainerPage(email1);
      classUnderTest0.addNewMemberToCurrentBoardBoardListContainerPage(email0);
      classUnderTest0.updateListBoardListContainerPage(listNames0, listNames1);
      classUnderTest0.addNewMemberToCurrentBoardBoardListContainerPage(email1);
      classUnderTest0.goToBoardListBoardListContainerPage();
  }

  //Test case number: 2
  /*
   * 21 covered goals:
   * Goal 1. main.ClassUnderTest.addNewBoardBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 29
   * Goal 2. main.ClassUnderTest.addNewCardToListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/CardText;)V: Line 149
   * Goal 3. main.ClassUnderTest.addNewListBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 169
   * Goal 4. main.ClassUnderTest.addNewMemberToCurrentBoardBoardListContainerPage(Lcustom_classes/Email;)V: Line 194
   * Goal 5. main.ClassUnderTest.addTagToCardCardDetails(Lcustom_classes/CardTag;)V: Line 452
   * Goal 6. main.ClassUnderTest.closeCardDetailsCardDetails()V: Line 471
   * Goal 7. main.ClassUnderTest.editDescriptionCardDetails(Lcustom_classes/CardText;Lcustom_classes/CardDescription;)V: Line 512
   * Goal 8. main.ClassUnderTest.goToBoardListBoardListContainerPage()V: Line 216
   * Goal 9. main.ClassUnderTest.goToBoardListBoardsContainerPage()V: Line 63
   * Goal 10. main.ClassUnderTest.goToBoardUsingNavbarBoardListContainerPage(Lcustom_classes/BoardNames;)V: Line 232
   * Goal 11. main.ClassUnderTest.goToBoardUsingNavbarBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 79
   * Goal 12. main.ClassUnderTest.goToCardOfListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/Id;)V: Line 256
   * Goal 13. main.ClassUnderTest.loginAsJohnLoginContainerPage()V: Line 601
   * Goal 14. main.ClassUnderTest.loginLoginContainerPage(Lcustom_classes/Email;Lcustom_classes/Passwords;)V: Line 627
   * Goal 15. main.ClassUnderTest.openAddNewBoardFormBoardsContainerPage()V: Line 98
   * Goal 16. main.ClassUnderTest.openAddNewListFormBoardListContainerPage()V: Line 276
   * Goal 17. main.ClassUnderTest.openEditDescriptionFormCardDetails()V: Line 529
   * Goal 18. main.ClassUnderTest.openUpdateListFormBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 334
   * Goal 19. main.ClassUnderTest.signOutBoardListContainerPage()V: Line 352
   * Goal 20. main.ClassUnderTest.signOutBoardsContainerPage()V: Line 112
   * Goal 21. main.ClassUnderTest.viewAllBoardsBoardsContainerPage()V: Line 127
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      Email email0 = Email.JOHNDOE;
      Passwords passwords0 = Passwords.JOHNDOE;
      classUnderTest0.loginLoginContainerPage(email0, passwords0);
      BoardNames boardNames0 = BoardNames.WORK_BOARD;
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      ListNames listNames0 = ListNames.ANOTHER_LIST;
      classUnderTest0.addNewListBoardListContainerPage(listNames0);
      int int0 = 2950;
      Id id0 = new Id(int0);
      classUnderTest0.openAddNewListFormBoardListContainerPage();
      ListNames listNames1 = ListNames.ANOTHER_LIST;
      classUnderTest0.openUpdateListFormBoardListContainerPage(listNames1);
      CardText cardText0 = CardText.LAUNDRY;
      classUnderTest0.addNewCardToListBoardListContainerPage(listNames0, cardText0);
      classUnderTest0.signOutBoardListContainerPage();
      Email email1 = Email.JOHNDOE;
      Passwords passwords1 = Passwords.JOHNDOE;
      classUnderTest0.loginLoginContainerPage(email1, passwords1);
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      classUnderTest0.goToBoardUsingNavbarBoardsContainerPage(boardNames0);
      classUnderTest0.goToCardOfListBoardListContainerPage(listNames1, id0);
      classUnderTest0.openEditDescriptionFormCardDetails();
      CardTag cardTag0 = CardTag.RED;
      classUnderTest0.addTagToCardCardDetails(cardTag0);
      CardText cardText1 = CardText.PERSONAL;
      CardDescription cardDescription0 = CardDescription.PERSONAL;
      classUnderTest0.editDescriptionCardDetails(cardText1, cardDescription0);
      CardTag cardTag1 = CardTag.PURPLE;
      classUnderTest0.addTagToCardCardDetails(cardTag1);
      CardTag cardTag2 = CardTag.GREEN;
      classUnderTest0.addTagToCardCardDetails(cardTag2);
      classUnderTest0.closeCardDetailsCardDetails();
      ListNames listNames2 = ListNames.ANOTHER_LIST;
      classUnderTest0.openUpdateListFormBoardListContainerPage(listNames2);
      classUnderTest0.goToBoardListBoardListContainerPage();
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      classUnderTest0.signOutBoardsContainerPage();
      classUnderTest0.loginAsJohnLoginContainerPage();
      classUnderTest0.goToBoardListBoardsContainerPage();
      classUnderTest0.viewAllBoardsBoardsContainerPage();
      classUnderTest0.goToBoardListBoardsContainerPage();
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      classUnderTest0.goToBoardUsingNavbarBoardListContainerPage(boardNames0);
      classUnderTest0.goToBoardListBoardListContainerPage();
      BoardNames boardNames1 = BoardNames.WORK_BOARD;
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames1);
      classUnderTest0.addNewMemberToCurrentBoardBoardListContainerPage(email1);
  }

  //Test case number: 3
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTest.addNewBoardBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 29
   * Goal 2. main.ClassUnderTest.addNewListBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 169
   * Goal 3. main.ClassUnderTest.goToBoardClickingOnItBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 45
   * Goal 4. main.ClassUnderTest.goToBoardListBoardsContainerPage()V: Line 63
   * Goal 5. main.ClassUnderTest.goToSignInPageSignUpContainerPage()V: Line 642
   * Goal 6. main.ClassUnderTest.goToSignUpLoginContainerPage()V: Line 587
   * Goal 7. main.ClassUnderTest.loginAsJohnLoginContainerPage()V: Line 601
   * Goal 8. main.ClassUnderTest.loginLoginContainerPage(Lcustom_classes/Email;Lcustom_classes/Passwords;)V: Line 624
   * Goal 9. main.ClassUnderTest.loginLoginContainerPage(Lcustom_classes/Email;Lcustom_classes/Passwords;)V: Line 627
   * Goal 10. main.ClassUnderTest.openAddNewBoardFormBoardsContainerPage()V: Line 98
   * Goal 11. main.ClassUnderTest.openAddNewListFormBoardListContainerPage()V: Line 276
   * Goal 12. main.ClassUnderTest.openAddNewMemberFormBoardListContainerPage()V: Line 292
   * Goal 13. main.ClassUnderTest.signOutBoardsContainerPage()V: Line 112
   * Goal 14. main.ClassUnderTest.updateListBoardListContainerPage(Lcustom_classes/ListNames;Lcustom_classes/ListNames;)V: Line 372
   * Goal 15. main.ClassUnderTest.viewAllBoardsBoardListContainerPage()V: Line 393
   */

  @Test(timeout = 1001000)
  public void test3()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      Email email0 = Email.ASD;
      Passwords passwords0 = Passwords.JOHNDOE;
      classUnderTest0.loginLoginContainerPage(email0, passwords0);
      classUnderTest0.loginAsJohnLoginContainerPage();
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      classUnderTest0.goToBoardListBoardsContainerPage();
      classUnderTest0.signOutBoardsContainerPage();
      classUnderTest0.goToSignUpLoginContainerPage();
      Email email1 = Email.JOHNDOE;
      Passwords passwords1 = Passwords.JOHNDOE;
      classUnderTest0.goToSignInPageSignUpContainerPage();
      classUnderTest0.loginLoginContainerPage(email1, passwords1);
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      BoardNames boardNames0 = BoardNames.MY_BOARD;
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      classUnderTest0.openAddNewListFormBoardListContainerPage();
      classUnderTest0.openAddNewListFormBoardListContainerPage();
      ListNames listNames0 = ListNames.PERSONAL_LIST;
      classUnderTest0.addNewListBoardListContainerPage(listNames0);
      ListNames listNames1 = ListNames.MY_LIST;
      classUnderTest0.updateListBoardListContainerPage(listNames0, listNames1);
      classUnderTest0.viewAllBoardsBoardListContainerPage();
      BoardNames boardNames1 = BoardNames.MY_BOARD;
      classUnderTest0.goToBoardClickingOnItBoardsContainerPage(boardNames1);
      classUnderTest0.openAddNewMemberFormBoardListContainerPage();
  }

  //Test case number: 4
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTest.addNewBoardBoardsContainerPage(Lcustom_classes/BoardNames;)V: Line 29
   * Goal 2. main.ClassUnderTest.addNewListBoardListContainerPage(Lcustom_classes/ListNames;)V: Line 169
   * Goal 3. main.ClassUnderTest.goToBoardListBoardListContainerPage()V: Line 216
   * Goal 4. main.ClassUnderTest.goToBoardListBoardsContainerPage()V: Line 63
   * Goal 5. main.ClassUnderTest.goToSignInPageSignUpContainerPage()V: Line 642
   * Goal 6. main.ClassUnderTest.goToSignUpLoginContainerPage()V: Line 587
   * Goal 7. main.ClassUnderTest.loginLoginContainerPage(Lcustom_classes/Email;Lcustom_classes/Passwords;)V: Line 627
   * Goal 8. main.ClassUnderTest.openAddNewBoardFormBoardsContainerPage()V: Line 98
   * Goal 9. main.ClassUnderTest.openAddNewListFormBoardListContainerPage()V: Line 276
   * Goal 10. main.ClassUnderTest.openAddNewMemberFormBoardListContainerPage()V: Line 292
   * Goal 11. main.ClassUnderTest.signOutBoardListContainerPage()V: Line 352
   * Goal 12. main.ClassUnderTest.signOutBoardsContainerPage()V: Line 112
   * Goal 13. main.ClassUnderTest.signUpFailurePasswordSignUpContainerPage(Lcustom_classes/PeopleNames;Lcustom_classes/PeopleNames;Lcustom_classes/Email;Lcustom_classes/Passwords;Lcustom_classes/Passwords;)V: Line 675
   * Goal 14. main.ClassUnderTest.signUpSignUpContainerPage(Lcustom_classes/PeopleNames;Lcustom_classes/PeopleNames;Lcustom_classes/Email;Lcustom_classes/Passwords;Lcustom_classes/Passwords;)V: Line 715
   * Goal 15. main.ClassUnderTest.signUpSignUpContainerPage(Lcustom_classes/PeopleNames;Lcustom_classes/PeopleNames;Lcustom_classes/Email;Lcustom_classes/Passwords;Lcustom_classes/Passwords;)V: Line 718
   */

  @Test(timeout = 1001000)
  public void test4()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSignUpLoginContainerPage();
      PeopleNames peopleNames0 = PeopleNames.ASD;
      PeopleNames peopleNames1 = PeopleNames.JOHN;
      Email email0 = Email.JOHNDOE;
      Passwords passwords0 = Passwords.JOHNDOE;
      Passwords passwords1 = Passwords.ASD;
      classUnderTest0.signUpFailurePasswordSignUpContainerPage(peopleNames0, peopleNames1, email0, passwords0, passwords1);
      classUnderTest0.goToSignInPageSignUpContainerPage();
      classUnderTest0.loginLoginContainerPage(email0, passwords0);
      Email email1 = Email.ASD;
      classUnderTest0.goToBoardListBoardsContainerPage();
      BoardNames boardNames0 = BoardNames.WORK_BOARD;
      ListNames listNames0 = ListNames.PERSONAL_LIST;
      classUnderTest0.openAddNewBoardFormBoardsContainerPage();
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      classUnderTest0.openAddNewMemberFormBoardListContainerPage();
      classUnderTest0.goToBoardListBoardListContainerPage();
      classUnderTest0.signOutBoardsContainerPage();
      classUnderTest0.goToSignUpLoginContainerPage();
      PeopleNames peopleNames2 = PeopleNames.MIKE;
      Passwords passwords2 = Passwords.ASD;
      PeopleNames peopleNames3 = PeopleNames.MIKE;
      Email email2 = Email.JOHNDOE;
      Passwords passwords3 = Passwords.JOHNDOE;
      classUnderTest0.signUpFailurePasswordSignUpContainerPage(peopleNames3, peopleNames2, email2, passwords2, passwords3);
      PeopleNames peopleNames4 = PeopleNames.LUKE;
      Passwords passwords4 = Passwords.ASD;
      classUnderTest0.signUpSignUpContainerPage(peopleNames4, peopleNames3, email1, passwords4, passwords2);
      PeopleNames peopleNames5 = PeopleNames.ASD;
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      classUnderTest0.addNewListBoardListContainerPage(listNames0);
      classUnderTest0.goToBoardListBoardListContainerPage();
      classUnderTest0.addNewBoardBoardsContainerPage(boardNames0);
      classUnderTest0.openAddNewListFormBoardListContainerPage();
      classUnderTest0.openAddNewListFormBoardListContainerPage();
      classUnderTest0.signOutBoardListContainerPage();
      classUnderTest0.goToSignUpLoginContainerPage();
      PeopleNames peopleNames6 = PeopleNames.LUKE;
      Email email3 = Email.ASD;
      Passwords passwords5 = Passwords.ASD;
      classUnderTest0.signUpSignUpContainerPage(peopleNames6, peopleNames3, email3, passwords5, passwords2);
      PeopleNames peopleNames7 = PeopleNames.MARK;
      Email email4 = Email.ASD;
      Passwords passwords6 = Passwords.ASD;
      Passwords passwords7 = Passwords.ASD;
      classUnderTest0.signUpSignUpContainerPage(peopleNames5, peopleNames7, email4, passwords6, passwords7);
  }
}
