/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 17 15:01:28 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Addresses;
import custom_classes.Cities;
import custom_classes.Dates;
import custom_classes.FirstNames;
import custom_classes.LastNames;
import custom_classes.PetNames;
import custom_classes.PetTypes;
import custom_classes.Telephones;
import custom_classes.VisitDescriptions;
import main.ClassUnderTestApogen;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTestApogen_ESTest extends ClassUnderTestApogen_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTestApogen.editOwnerEditOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 297
   * Goal 2. main.ClassUnderTestApogen.formVisitsPage(Lcustom_classes/Dates;Lcustom_classes/VisitDescriptions;)V: Line 57
   * Goal 3. main.ClassUnderTestApogen.goToAddNewPetOwnerInformationPage()V: Line 114
   * Goal 4. main.ClassUnderTestApogen.goToEditOwnerOwnerInformationPage()V: Line 128
   * Goal 5. main.ClassUnderTestApogen.goToEditPetThroghEditLinkOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 145
   * Goal 6. main.ClassUnderTestApogen.goToEditPetThroughNameOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 166
   * Goal 7. main.ClassUnderTestApogen.goToIndexOwnerInformationPage()V: Line 185
   * Goal 8. main.ClassUnderTestApogen.goToIndexVetsPage()V: Line 27
   * Goal 9. main.ClassUnderTestApogen.goToNewOwnerIndexPage()V: Line 218
   * Goal 10. main.ClassUnderTestApogen.goToOwnerInformationOwnersPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;)V: Line 74
   * Goal 11. main.ClassUnderTestApogen.goToOwnersIndexPage()V: Line 232
   * Goal 12. main.ClassUnderTestApogen.goToVetsIndexPage()V: Line 246
   * Goal 13. main.ClassUnderTestApogen.goToVisitsOwnerInformationPage(Lcustom_classes/PetNames;)V: Line 200
   * Goal 14. main.ClassUnderTestApogen.submitNewPetPage(Lcustom_classes/PetNames;Lcustom_classes/Dates;Lcustom_classes/PetTypes;)V: Line 42
   * Goal 15. main.ClassUnderTestApogen.submitOwnerFormNewOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 279
   */

  @Test(timeout = 1001000)
  public void test0()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToNewOwnerIndexPage();
      FirstNames firstNames0 = FirstNames.EDUARDO;
      LastNames lastNames0 = LastNames.FRANKLIN;
      Addresses addresses0 = Addresses.LIBERTY;
      Cities cities0 = Cities.MCFARLAND;
      Telephones telephones0 = Telephones.PHONE2;
      classUnderTestApogen0.submitOwnerFormNewOwnerPage(firstNames0, lastNames0, addresses0, cities0, telephones0);
      FirstNames firstNames1 = FirstNames.HAROLD;
      LastNames lastNames1 = LastNames.FRANKLIN;
      FirstNames firstNames2 = FirstNames.EDUARDO;
      classUnderTestApogen0.goToOwnerInformationOwnersPage(firstNames2, lastNames1);
      PetNames petNames0 = PetNames.ROSY;
      Dates dates0 = Dates.DATE3;
      VisitDescriptions visitDescriptions0 = VisitDescriptions.TWO;
      classUnderTestApogen0.goToIndexOwnerInformationPage();
      classUnderTestApogen0.goToOwnersIndexPage();
      classUnderTestApogen0.goToOwnerInformationOwnersPage(firstNames0, lastNames0);
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      PetTypes petTypes0 = PetTypes.CAT;
      classUnderTestApogen0.submitNewPetPage(petNames0, dates0, petTypes0);
      PetNames petNames1 = PetNames.ROSY;
      classUnderTestApogen0.goToEditPetThroughNameOwnerInformationPage(petNames1);
      PetTypes petTypes1 = PetTypes.CAT;
      classUnderTestApogen0.submitNewPetPage(petNames0, dates0, petTypes1);
      classUnderTestApogen0.goToEditPetThroghEditLinkOwnerInformationPage(petNames0);
      classUnderTestApogen0.submitNewPetPage(petNames1, dates0, petTypes0);
      classUnderTestApogen0.goToEditOwnerOwnerInformationPage();
      LastNames lastNames2 = LastNames.FRANKLIN;
      Addresses addresses1 = Addresses.LIBERTY;
      Telephones telephones1 = Telephones.PHONE3;
      classUnderTestApogen0.editOwnerEditOwnerPage(firstNames1, lastNames2, addresses1, cities0, telephones1);
      classUnderTestApogen0.goToAddNewPetOwnerInformationPage();
      Dates dates1 = Dates.DATE4;
      classUnderTestApogen0.submitNewPetPage(petNames1, dates1, petTypes1);
      classUnderTestApogen0.goToVisitsOwnerInformationPage(petNames1);
      classUnderTestApogen0.formVisitsPage(dates1, visitDescriptions0);
      classUnderTestApogen0.goToVisitsOwnerInformationPage(petNames1);
      classUnderTestApogen0.formVisitsPage(dates0, visitDescriptions0);
      classUnderTestApogen0.goToEditPetThroghEditLinkOwnerInformationPage(petNames0);
      PetTypes petTypes2 = PetTypes.LIZARD;
      classUnderTestApogen0.submitNewPetPage(petNames1, dates0, petTypes2);
      PetNames petNames2 = PetNames.ROSY;
      classUnderTestApogen0.goToEditPetThroughNameOwnerInformationPage(petNames2);
      PetNames petNames3 = PetNames.ROSY;
      classUnderTestApogen0.submitNewPetPage(petNames3, dates0, petTypes2);
      classUnderTestApogen0.goToVisitsOwnerInformationPage(petNames3);
      Dates dates2 = Dates.DATE1;
      classUnderTestApogen0.formVisitsPage(dates2, visitDescriptions0);
      classUnderTestApogen0.goToVisitsOwnerInformationPage(petNames1);
      Dates dates3 = Dates.DATE1;
      VisitDescriptions visitDescriptions1 = VisitDescriptions.THREE;
      classUnderTestApogen0.formVisitsPage(dates3, visitDescriptions1);
      classUnderTestApogen0.goToIndexOwnerInformationPage();
      classUnderTestApogen0.goToVetsIndexPage();
      classUnderTestApogen0.goToIndexVetsPage();
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * Goal 1. main.ClassUnderTestApogen.goToIndexWelcomePage()V: Line 311
   * Goal 2. main.ClassUnderTestApogen.goToOwnersWelcomePage()V: Line 339
   * Goal 3. main.ClassUnderTestApogen.goToWelcomeIndexPage()V: Line 260
   */

  @Test(timeout = 1001000)
  public void test1()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToIndexWelcomePage();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToOwnersWelcomePage();
  }

  //Test case number: 2
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTestApogen.goToIndexOwnerInformationPage()V: Line 185
   * Goal 2. main.ClassUnderTestApogen.goToNewOwnerWelcomePage()V: Line 325
   * Goal 3. main.ClassUnderTestApogen.goToOwnerInformationOwnersPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;)V: Line 74
   * Goal 4. main.ClassUnderTestApogen.goToOwnersIndexPage()V: Line 232
   * Goal 5. main.ClassUnderTestApogen.goToWelcomeIndexPage()V: Line 260
   * Goal 6. main.ClassUnderTestApogen.searchFilterOwnersPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;)V: Line 95
   * Goal 7. main.ClassUnderTestApogen.submitOwnerFormNewOwnerPage(Lcustom_classes/FirstNames;Lcustom_classes/LastNames;Lcustom_classes/Addresses;Lcustom_classes/Cities;Lcustom_classes/Telephones;)V: Line 279
   */

  @Test(timeout = 1001000)
  public void test2()  throws Throwable  {
      ClassUnderTestApogen classUnderTestApogen0 = new ClassUnderTestApogen();
      classUnderTestApogen0.goToWelcomeIndexPage();
      classUnderTestApogen0.goToNewOwnerWelcomePage();
      FirstNames firstNames0 = FirstNames.HAROLD;
      LastNames lastNames0 = LastNames.RODRIQUEZ;
      Addresses addresses0 = Addresses.LIBERTY;
      Cities cities0 = Cities.MCFARLAND;
      Telephones telephones0 = Telephones.PHONE1;
      classUnderTestApogen0.submitOwnerFormNewOwnerPage(firstNames0, lastNames0, addresses0, cities0, telephones0);
      LastNames lastNames1 = LastNames.RODRIQUEZ;
      classUnderTestApogen0.goToOwnerInformationOwnersPage(firstNames0, lastNames1);
      classUnderTestApogen0.goToIndexOwnerInformationPage();
      classUnderTestApogen0.goToOwnersIndexPage();
      FirstNames firstNames1 = FirstNames.HAROLD;
      classUnderTestApogen0.searchFilterOwnersPage(firstNames1, lastNames0);
  }
}
